# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/arif/Main/Programs/Software/new_try/my_proj/component/ui/table_bottom.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableBottom(object):
    def setupUi(self, TableBottom):
        TableBottom.setObjectName("TableBottom")
        TableBottom.resize(612, 69)
        self.gridLayout = QtWidgets.QGridLayout(TableBottom)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(TableBottom)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PushButton = PushButton(self.widget)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout.addWidget(self.PushButton)
        self.PushButton_2 = PushButton(self.widget)
        self.PushButton_2.setObjectName("PushButton_2")
        self.horizontalLayout.addWidget(self.PushButton_2)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.PushButton_3 = PushButton(TableBottom)
        self.PushButton_3.setObjectName("PushButton_3")
        self.gridLayout.addWidget(self.PushButton_3, 0, 1, 1, 1, QtCore.Qt.AlignRight)

        self.retranslateUi(TableBottom)
        QtCore.QMetaObject.connectSlotsByName(TableBottom)

    def retranslateUi(self, TableBottom):
        _translate = QtCore.QCoreApplication.translate
        TableBottom.setWindowTitle(_translate("TableBottom", "Form"))
        self.PushButton.setText(_translate("TableBottom", "Previous"))
        self.PushButton_2.setText(_translate("TableBottom", "Next"))
        self.PushButton_3.setText(_translate("TableBottom", "Export"))
from qfluentwidgets import PushButton
